baseURL: https://reenakvenkatesh.netlify.app/
languageCode: en-us
title: Reena Venkatesh's Portfolio website
theme: forty
googleAnalytics: ''
disqusShortname: ''
params:
  banner:
    buttonText: Start!
    subtitle: |-
      ABOUT ME, WHAT I LOVE,
      AND THE R PROJECTS I HAVE COMPLETED ~
    title: Reena K Venkatesh
  blog: {}
  contact:
    address:
      - city: London, NW1 4SA
        country: United Kingdom
        street: Regent's Park
        title: LBS Address
    buttonClear: Clear
    buttonSend: Send message
    email:
      - email: rkvenkatesh.mfa2022@london.edu
        title: Email
    enable: yes
    phone:
      - phone: connect with me on linkedin!
        title: Phone
  custom_css: []
  custom_js: []
  description: A portfolio website about me and my projects. 
  error404:
    heading: Page couldn't be found
    text: Please visit [this page](/)
  favicon: favicon.ico
  footer:
    copyright: Reena K Venkatesh
    enable: yes
#    quicklinks:
#      - alt: HTML5 UP
#        text: 'Design: '
#        url: https://www.html5up.net
    social:
#      - icon: fa-twitter
#        label: Twitter
#        url: https://www.twitter.com
#      - icon: fa-facebook
#        label: Facebook
#        url: https://www.facebook.com
      - icon: fa-instagram
        label: Instagram
        url: https://www.instagram.com/reeeennaaa/
      - icon: fa-github
        label: GitHub
        url: https://github.com/reenalisha24
      - icon: fa-linkedin
        label: LinkedIn
        url: https://www.linkedin.com/in/reenakv/
  image: ''
  name: Reena
  navigation:
    button1:
      - name: Home
        url: '#'
    links:
      - name: About me
        url: blogs/cv
      - name: What I enjoy
        url: blogs/art
      - name: Rproj - Bike Rentals
        url: blogs/bike
      - name: Rproj - Rio De Janeiro
        url: blogs/rio
    menu: Menu
    subtitle: MFA 2022
    title: Reena's Portfolio Website
  tiles:
    enable: yes
    showcase:
      - image: me.jpg
        subtitle: My CV
        title: About Me
        url: blogs/cv
      - image: artbanner.jpg
        subtitle: My Art
        title: What I enjoy
        url: blogs/art #slug in rmd file
      - image: bike.jpg
        subtitle: Monthly changes in bike rentals over the past 5 years
        title: Rproject - Analysis of London Bike Rentals
        url: blogs/bike
      - image: rio.jpeg
        subtitle: Conducting a Regression Analysis
        title: Rproject - Analysis of Airbnbs in Rio De Janeiro
        url: blogs/rio
#      - image: pic05.jpg
#        subtitle: Ipsum Dolor Sit Amet
#        title: Consequat
#        url: blogs/ipsum
#      - image: pic06.jpg
#        subtitle: Feugiat Amet Tempus
#        title: Etiam
#        url: blogs/ipsum
  two:
    buttonText: Back to the top
    enable: yes
    subtitle: "Thank you for taking the time to look through my website"
    title: That's it for now!
    url: '#'
